/* ============================================================
   ÉTAT HARDWARE
   ============================================================ */
const hw = { gpu:'Auto', vram:8, bw:448, ram:8, cores: navigator.hardwareConcurrency||4 };

/* ============================================================
   LISTE GPU COMPLÈTE
   ============================================================ */
const GPU_LIST = [
  /* === NVIDIA RTX Série 50 === */
  { g:'RTX 50',  label:'RTX 5090 (32 GB)',              vram:32,  bw:1792 , tier:10 },
  { g:'RTX 50',  label:'RTX 5080 (16 GB)',              vram:16,  bw:960 , tier:10  },
  { g:'RTX 50',  label:'RTX 5070 Ti (16 GB)',           vram:16,  bw:896 , tier:9 },
  { g:'RTX 50',  label:'RTX 5070 (12 GB)',              vram:12,  bw:672 , tier:9 },
  { g:'RTX 50',  label:'RTX 5060 Ti (16 GB)',           vram:16,  bw:448, tier:9  },
  { g:'RTX 50',  label:'RTX 5060 Ti (8 GB)',            vram:8,   bw:448, tier:9  },
  { g:'RTX 50',  label:'RTX 5060 (8 GB)',               vram:8,   bw:448, tier:8  },
  { g:'RTX 50',  label:'RTX 5050 (8 GB)',               vram:8,   bw:320, tier:8  },
  /* === NVIDIA RTX Série 40 === */
  { g:'RTX 40',  label:'RTX 4090 (24 GB)',              vram:24,  bw:1008, tier:9 },
  { g:'RTX 40',  label:'RTX 4080 Super (16 GB)',        vram:16,  bw:736 , tier:9 },
  { g:'RTX 40',  label:'RTX 4080 (16 GB)',              vram:16,  bw:717, tier:9  },
  { g:'RTX 40',  label:'RTX 4070 Ti Super (16 GB)',     vram:16,  bw:672, tier:8  },
  { g:'RTX 40',  label:'RTX 4070 Ti (12 GB)',           vram:12,  bw:504 , tier:8 },
  { g:'RTX 40',  label:'RTX 4070 Super (12 GB)',        vram:12,  bw:504 , tier:8 },
  { g:'RTX 40',  label:'RTX 4070 (12 GB)',              vram:12,  bw:504 , tier:8 },
  { g:'RTX 40',  label:'RTX 4060 Ti (16 GB)',           vram:16,  bw:288, tier:7   },
  { g:'RTX 40',  label:'RTX 4060 Ti (8 GB)',            vram:8,   bw:288, tier:7   },
  { g:'RTX 40',  label:'RTX 4060 (8 GB)',               vram:8,   bw:272 , tier:7  },
  { g:'RTX 40',  label:'RTX 4050 (6 GB)',               vram:6,   bw:192 , tier:6 },
  /* === NVIDIA RTX Série 30 === */
  { g:'RTX 30',  label:'RTX 3090 Ti (24 GB)',           vram:24,  bw:1008 , tier:7},
  { g:'RTX 30',  label:'RTX 3090 (24 GB)',              vram:24,  bw:936 , tier:7 },
  { g:'RTX 30',  label:'RTX 3080 Ti (12 GB)',           vram:12,  bw:912 , tier:7 },
  { g:'RTX 30',  label:'RTX 3080 12GB',                 vram:12,  bw:912 , tier:7 },
  { g:'RTX 30',  label:'RTX 3080 10GB',                 vram:10,  bw:760  , tier:7},
  { g:'RTX 30',  label:'RTX 3070 Ti (8 GB)',            vram:8,   bw:608 , tier:6 },
  { g:'RTX 30',  label:'RTX 3070 (8 GB)',               vram:8,   bw:448 , tier:6 },
  { g:'RTX 30',  label:'RTX 3060 Ti (8 GB)',            vram:8,   bw:448  , tier:6},
  { g:'RTX 30',  label:'RTX 3060 (12 GB)',              vram:12,  bw:360 , tier:5  },
  { g:'RTX 30',  label:'RTX 3050 (8 GB)',               vram:8,   bw:224 , tier:5  },
  { g:'RTX 30',  label:'RTX 3050 (6 GB)',               vram:6,   bw:168 , tier:5  },
  /* === NVIDIA RTX Série 20 === */
  { g:'RTX 20',  label:'RTX 2080 Ti (11 GB)',           vram:11,  bw:616 , tier:5  },
  { g:'RTX 20',  label:'RTX 2080 Super (8 GB)',         vram:8,   bw:496 , tier:5  },
  { g:'RTX 20',  label:'RTX 2080 (8 GB)',               vram:8,   bw:448 , tier:5  },
  { g:'RTX 20',  label:'RTX 2070 Super (8 GB)',         vram:8,   bw:448 , tier:5  },
  { g:'RTX 20',  label:'RTX 2070 (8 GB)',               vram:8,   bw:448 , tier:4 },
  { g:'RTX 20',  label:'RTX 2060 Super (8 GB)',         vram:8,   bw:448, tier:4  },
  { g:'RTX 20',  label:'RTX 2060 (6 GB)',               vram:6,   bw:336, tier:4  },
  /* === NVIDIA GTX Série 10 === */
  { g:'GTX 10',  label:'GTX 1080 Ti (11 GB)',           vram:11,  bw:484 , tier:3 },
  { g:'GTX 10',  label:'GTX 1080 (8 GB)',               vram:8,   bw:320 , tier:3 },
  { g:'GTX 10',  label:'GTX 1070 Ti (8 GB)',            vram:8,   bw:256  , tier:3},
  { g:'GTX 10',  label:'GTX 1070 (8 GB)',               vram:8,   bw:256 , tier:3 },
  { g:'GTX 10',  label:'GTX 1060 6GB',                  vram:6,   bw:192 , tier:2 },
  { g:'GTX 10',  label:'GTX 1060 3GB',                  vram:3,   bw:192, tier:2  },
  { g:'GTX 10',  label:'GTX 1050 Ti (4 GB)',            vram:4,   bw:112, tier:2  },
  { g:'GTX 10',  label:'GTX 1050 (2 GB)',               vram:2,   bw:112 , tier:1 },
  /* === NVIDIA Quadro / RTX Pro === */
  /* Verified against NVIDIA product pages / datasheets (2026-04):
     RTX 6000 Ada 960, RTX 5000 Ada 576, RTX 4000 SFF Ada 280,
     RTX A6000 768, RTX A5000 768, RTX A4000 448, RTX A2000 288,
     Quadro RTX 8000 672, Quadro RTX 6000 672.
     Pending direct datasheet recheck: RTX 4500 Ada, RTX 4000 Ada. */
  { g:'Quadro',  label:'RTX 6000 Ada (48 GB)',          vram:48,  bw:960 , tier:9 },
  { g:'Quadro',  label:'RTX 5000 Ada (32 GB)',          vram:32,  bw:576, tier:8  },
  { g:'Quadro',  label:'RTX 4500 Ada (24 GB)',          vram:24,  bw:432, tier:8  },
  { g:'Quadro',  label:'RTX 4000 Ada (20 GB)',          vram:20,  bw:432, tier:8  },
  { g:'Quadro',  label:'RTX 4000 SFF Ada (20 GB)',      vram:20,  bw:280 , tier:7 },
  { g:'Quadro',  label:'RTX A6000 (48 GB)',             vram:48,  bw:768 , tier:7 },
  { g:'Quadro',  label:'RTX A5000 (24 GB)',             vram:24,  bw:768 , tier:7 },
  { g:'Quadro',  label:'RTX A4000 (16 GB)',             vram:16,  bw:448 , tier:6 },
  { g:'Quadro',  label:'RTX A2000 (12 GB)',             vram:12,  bw:288 , tier:5  },
  { g:'Quadro',  label:'Quadro RTX 8000 (48 GB)',       vram:48,  bw:672  , tier:5 },
  { g:'Quadro',  label:'Quadro RTX 6000 (24 GB)',       vram:24,  bw:672 , tier:5  },
  /* === AMD Radeon RX === */
  { g:'AMD RX',  label:'RX 7900 XTX (24 GB)',           vram:24,  bw:960, tier:8  },
  { g:'AMD RX',  label:'RX 7900 XT (20 GB)',            vram:20,  bw:800, tier:8  },
  { g:'AMD RX',  label:'RX 7800 XT (16 GB)',            vram:16,  bw:624 , tier:7 },
  { g:'AMD RX',  label:'RX 7700 XT (12 GB)',            vram:12,  bw:432 , tier:7 },
  { g:'AMD RX',  label:'RX 7600 (8 GB)',                vram:8,   bw:288 , tier:6 },
  { g:'AMD RX',  label:'RX 6900 XT (16 GB)',            vram:16,  bw:512 , tier:6 },
  { g:'AMD RX',  label:'RX 6800 XT (16 GB)',            vram:16,  bw:512 , tier:6 },
  { g:'AMD RX',  label:'RX 6700 XT (12 GB)',            vram:12,  bw:384 , tier:5  },
  { g:'AMD RX',  label:'RX 6600 (8 GB)',                vram:8,   bw:224  , tier:4},
  /* === Apple Silicon === */
  { g:'Apple M',  label:'M4 Max — 128 GB',              vram:128, bw:546 , tier:9 },
  { g:'Apple M',  label:'M4 Max — 64 GB',               vram:64,  bw:546, tier:9  },
  { g:'Apple M',  label:'M4 Max — 36 GB',               vram:36,  bw:546 , tier:9 },
  { g:'Apple M',  label:'M4 Pro — 48 GB',               vram:48,  bw:273 , tier:9 },
  { g:'Apple M',  label:'M4 Pro — 24 GB',               vram:24,  bw:273, tier:9  },
  { g:'Apple M',  label:'M4 — 16 GB',                   vram:16,  bw:120, tier:8  },
  { g:'Apple M',  label:'M4 — 32 GB',                   vram:32,  bw:120, tier:8  },
  { g:'Apple M',  label:'M3 Ultra — 192 GB',            vram:192, bw:800, tier:9 },
  { g:'Apple M',  label:'M3 Max — 128 GB',              vram:128, bw:400, tier:8  },
  { g:'Apple M',  label:'M3 Max — 64 GB',               vram:64,  bw:400, tier:8  },
  { g:'Apple M',  label:'M3 Pro — 36 GB',               vram:36,  bw:150, tier:8  },
  { g:'Apple M',  label:'M3 Pro — 18 GB',               vram:18,  bw:150, tier:8  },
  { g:'Apple M',  label:'M3 — 24 GB',                   vram:24,  bw:100, tier:7  },
  { g:'Apple M',  label:'M3 — 16 GB',                   vram:16,  bw:100, tier:7  },
  { g:'Apple M',  label:'M3 — 8 GB',                    vram:8,   bw:100, tier:7  },
  { g:'Apple M',  label:'M2 Ultra — 192 GB',            vram:192, bw:800, tier:8  },
  { g:'Apple M',  label:'M2 Max — 96 GB',               vram:96,  bw:400, tier:7  },
  { g:'Apple M',  label:'M2 Max — 64 GB',               vram:64,  bw:400, tier:7  },
  { g:'Apple M',  label:'M2 Pro — 32 GB',               vram:32,  bw:200, tier:7  },
  { g:'Apple M',  label:'M2 Pro — 16 GB',               vram:16,  bw:200, tier:7 },
  { g:'Apple M',  label:'M2 — 24 GB',                   vram:24,  bw:100 , tier:6 },
  { g:'Apple M',  label:'M2 — 16 GB',                   vram:16,  bw:100 , tier:6 },
  { g:'Apple M',  label:'M2 — 8 GB',                    vram:8,   bw:100  , tier:6},
  { g:'Apple M',  label:'M1 Ultra — 128 GB',            vram:128, bw:800 , tier:7 },
  { g:'Apple M',  label:'M1 Max — 64 GB',               vram:64,  bw:400 , tier:6},
  { g:'Apple M',  label:'M1 Max — 32 GB',               vram:32,  bw:400 , tier:6},
  { g:'Apple M',  label:'M1 Pro — 32 GB',               vram:32,  bw:200 , tier:6 },
  { g:'Apple M',  label:'M1 Pro — 16 GB',               vram:16,  bw:200 , tier:6 },
  { g:'Apple M',  label:'M1 — 16 GB',                   vram:16,  bw:68  , tier:5  },
  { g:'Apple M',  label:'M1 — 8 GB',                    vram:8,   bw:68  , tier:5  },
  /* === Ryzen APU / iGPU === */
  { g:'Ryzen APU', label:'Ryzen AI 9 HX 370 (4 GB)',    vram:4,   bw:128 , tier:5  },
  { g:'Ryzen APU', label:'Ryzen 9 7940HS iGPU (3 GB)', vram:3,   bw:102, tier:4  },
  { g:'Ryzen APU', label:'Radeon 780M iGPU (3 GB)',     vram:3,   bw:102, tier:4  },
  { g:'Ryzen APU', label:'Radeon 760M iGPU (2 GB)',     vram:2,   bw:64, tier:3   },
  { g:'Ryzen APU', label:'Radeon 680M iGPU (2 GB)',     vram:2,   bw:64 , tier:3  },
  { g:'Ryzen APU', label:'Ryzen 5 5600G iGPU (2 GB)',   vram:2,   bw:51 , tier:2   },
  /* === Raspberry Pi / Edge === */
  { g:'Raspberry', label:'Raspberry Pi 5 (8 GB)',        vram:8,   bw:17 , tier:2   },
  { g:'Raspberry', label:'Raspberry Pi 5 (4 GB)',        vram:4,   bw:17  , tier:2 },
  { g:'Raspberry', label:'Raspberry Pi 4B (8 GB)',       vram:8,   bw:14 , tier:1  },
  { g:'Raspberry', label:'Raspberry Pi 4B (4 GB)',       vram:4,   bw:14 , tier:1  },
  { g:'Raspberry', label:'Raspberry Pi 4B (2 GB)',       vram:2,   bw:14  , tier:1 },
  /* === Data center === */
  /* Verified against NVIDIA specs / datasheets (2026-04):
     H200 SXM 4800, H100 SXM 3350, H100 PCIe 2000,
     A100 SXM 2039, A100 PCIe 1555, A40 696. */
  { g:'Data Center', label:'H200 SXM (141 GB)',          vram:141, bw:4800 , tier:10 },
  { g:'Data Center', label:'H100 SXM (80 GB)',           vram:80,  bw:3350 , tier:10 },
  { g:'Data Center', label:'H100 PCIe (80 GB)',          vram:80,  bw:2000, tier:9 },
  { g:'Data Center', label:'A100 SXM (80 GB)',           vram:80,  bw:2039, tier:9 },
  { g:'Data Center', label:'A100 PCIe (40 GB)',          vram:40,  bw:1555, tier:8 },
  { g:'Data Center', label:'A40 (48 GB)',                vram:48,  bw:696, tier:7  },
  /* === CPU uniquement === */
  { g:'CPU', label:'CPU uniquement — RAM partagée',      vram:0,   bw:50 , tier:1  },
];

/* ============================================================
   DONNÉES MODÈLES IA
   Champs : name, provider, params (milliards), vram (GB),
            ctx (contexte), lic (classe CSS), licLabel,
            caps (badges : key/eye/q/star/moe),
            tasks (filtrable : chat/code/reasoning/vision/edge/multilingual),
            abliterated (bool), arch, released, age
   ============================================================ */
const MODELS = [
  /* ── Ultra-légers ──────────────────────────────────────── */
  {name:'Qwen 3 0.6B',            provider:'Alibaba',    params:0.6,  vram:0.8,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','edge'],               tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'Qwen 3.5 0.8B',          provider:'Alibaba',    params:0.8,  vram:0.9,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','edge'],               tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2026-02', age:'2mo ago'},
  {name:'TinyLlama 1.1B',         provider:'Community',  params:1.1,  vram:1.1,  ctx:'2K',    lic:'apache', licLabel:'Apache 2.0',          caps:['edge'],                  tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2024-01', age:'2y ago'},
  {name:'Llama 3.2 1B',           provider:'Meta',       params:1,    vram:1.0,  ctx:'128K',  lic:'llama',  licLabel:'Llama 3.2 Community', caps:['chat','edge'],             tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2024-09', age:'1 year ago'},
  {name:'Gemma 3 1B',             provider:'Google',     params:1,    vram:1.0,  ctx:'32K',   lic:'gemma',  licLabel:'Gemma',               caps:['edge'],                  tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2025-03', age:'1 year ago'},
  {name:'DeepSeek R1 1.5B',       provider:'DeepSeek',   params:1.5,  vram:1.3,  ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning','edge'],               tasks:['reasoning','edge'],         abliterated:false, arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'Qwen 2.5 Coder 1.5B',    provider:'Alibaba',    params:1.5,  vram:1.3,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['code','edge'],                  tasks:['code','edge'],              abliterated:false, arch:'Dense', released:'2024-11', age:'1 year ago'},
  {name:'Qwen 3 1.7B',            provider:'Alibaba',    params:1.7,  vram:1.4,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','multi'],               tasks:['chat','multilingual'],      abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'Gemma 2 2B',             provider:'Google',     params:2,    vram:1.5,  ctx:'8K',    lic:'gemma',  licLabel:'Gemma',               caps:['edge'],                  tasks:['chat','edge'],              abliterated:false, arch:'Dense', released:'2024-06', age:'1 year ago'},
  {name:'Qwen 3.5 2B',            provider:'Alibaba',    params:2,    vram:1.5,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','multi'],               tasks:['chat','multilingual'],      abliterated:false, arch:'Dense', released:'2026-02', age:'2mo ago'},
  /* ── 2-4 GB ─────────────────────────────────────────────── */
  {name:'Llama 3.2 3B',           provider:'Meta',       params:3,    vram:2.0,  ctx:'128K',  lic:'llama',  licLabel:'Llama 3.2 Community', caps:['chat','code'],             tasks:['chat','code'],              abliterated:false, arch:'Dense', released:'2024-09', age:'1 year ago'},
  {name:'SmolLM3 3B',             provider:'HuggingFace',params:3,    vram:2.0,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:[],                  tasks:['chat','reasoning'],         abliterated:false, arch:'Dense', released:'2025-07', age:'9mo ago'},
  {name:'Phi-4 Mini Reasoning',   provider:'Microsoft',  params:3.8,  vram:2.4,  ctx:'16K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning'],               tasks:['reasoning'],               abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'Phi-3.5 Mini',           provider:'Microsoft',  params:3.8,  vram:2.4,  ctx:'128K',  lic:'mit',    licLabel:'MIT',                 caps:['code'],                  tasks:['reasoning','code','chat'],  abliterated:false, arch:'Dense', released:'2024-08', age:'1 year ago'},
  {name:'Qwen 3 4B',              provider:'Alibaba',    params:4,    vram:2.5,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['chat','reasoning','code'],         tasks:['chat','code'],              abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'Gemma 3 4B',             provider:'Google',     params:4,    vram:2.5,  ctx:'128K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['chat','vision'],            abliterated:false, arch:'Dense', released:'2025-03', age:'1 year ago'},
  {name:'Qwen 3.5 4B',            provider:'Alibaba',    params:4,    vram:2.5,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','multi'],               tasks:['chat','multilingual'],      abliterated:false, arch:'Dense', released:'2026-02', age:'2mo ago'},
  {name:'Gemma 4 E2B IT',         provider:'Google',     params:5,    vram:3.1,  ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['chat','vision'],            abliterated:false, arch:'Dense', released:'2026-04', age:'5d ago'},
  {name:'Gemma 4 E2B',            provider:'Google',     params:5,    vram:3.1,  ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['vision'],                   abliterated:false, arch:'Dense', released:'2026-04', age:'5d ago'},
  {name:'Gemma 4 E4B IT',         provider:'Google',     params:8,    vram:4.6,  ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['chat','vision'],            abliterated:false, arch:'Dense', released:'2026-04', age:'5d ago'},
  {name:'Gemma 4 E4B',            provider:'Google',     params:8,    vram:4.6,  ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['vision'],                   abliterated:false, arch:'Dense', released:'2026-04', age:'5d ago'},
  /* ── 4-8 GB ─────────────────────────────────────────────── */
  {name:'Mistral 7B v0.3',        provider:'Mistral AI', params:7,    vram:4.1,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['chat'],             tasks:['chat','reasoning'],         abliterated:false, arch:'Dense', released:'2024-05', age:'2y ago'},
  {name:'Mistral 7B v0.3 Abliterated', provider:'Community', params:7, vram:4.1, ctx:'32K',   lic:'mit',   licLabel:'MIT',                 caps:['chat'],             tasks:['chat','reasoning'],         abliterated:true,  arch:'Dense', released:'2024-06', age:'1 year ago'},
  {name:'Qwen 2.5 7B',            provider:'Alibaba',    params:7,    vram:4.1,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','code','multi'],             tasks:['chat','multilingual','code'],abliterated:false, arch:'Dense', released:'2024-09', age:'1 year ago'},
  {name:'Qwen 2.5 7B Abliterated',provider:'Community',  params:7,    vram:4.1,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','multi'],             tasks:['chat','multilingual'],      abliterated:true,  arch:'Dense', released:'2024-10', age:'1 year ago'},
  {name:'Qwen 2.5 Coder 7B',      provider:'Alibaba',    params:7,    vram:4.1,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','code'],             tasks:['code'],                     abliterated:false, arch:'Dense', released:'2024-11', age:'1 year ago'},
  {name:'DeepSeek R1 Distill 7B', provider:'DeepSeek',   params:7,    vram:4.1,  ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning'],               tasks:['reasoning'],               abliterated:false, arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'Llama 3.1 8B',           provider:'Meta',       params:8,    vram:4.6,  ctx:'128K',  lic:'llama',  licLabel:'Llama 3.1 Community', caps:['chat','star','code'],      tasks:['chat','code','reasoning'],  abliterated:false, arch:'Dense', released:'2024-07', age:'1 year ago'},
  {name:'Llama 3.1 8B Abliterated',provider:'Community', params:8,    vram:4.6,  ctx:'128K',  lic:'mit',    licLabel:'MIT',                 caps:['chat','star','code'],      tasks:['chat','code','reasoning'],  abliterated:true,  arch:'Dense', released:'2024-08', age:'1 year ago'},
  {name:'Qwen 3 8B',              provider:'Alibaba',    params:8,    vram:4.6,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','reasoning','code'],         tasks:['chat','code','reasoning'],  abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'Ministral 8B',           provider:'Mistral AI', params:8,    vram:4.6,  ctx:'32K',   lic:'mrl',    licLabel:'MRL',                 caps:['chat'],             tasks:['chat'],                     abliterated:false, arch:'Dense', released:'2024-10', age:'1 year ago'},
  {name:'Qwen 3.5 9B',            provider:'Alibaba',    params:9,    vram:5.1,  ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','vision','star'],  tasks:['chat','vision'],            abliterated:false, arch:'Dense', released:'2026-02', age:'2mo ago'},
  {name:'Gemma 2 9B',             provider:'Google',     params:9,    vram:5.1,  ctx:'8K',    lic:'gemma',  licLabel:'Gemma',               caps:[],                  tasks:['chat','reasoning'],         abliterated:false, arch:'Dense', released:'2024-06', age:'2y ago'},
  {name:'Gemma 2 9B Abliterated', provider:'Community',  params:9,    vram:5.1,  ctx:'8K',    lic:'mit',    licLabel:'MIT',                 caps:[],                  tasks:['chat','reasoning'],         abliterated:true,  arch:'Dense', released:'2024-07', age:'1 year ago'},
  {name:'GLM-4 9B',               provider:'Zhipu AI',   params:9,    vram:5.1,  ctx:'128K',  lic:'glm',    licLabel:'GLM-4',               caps:['chat','code','multi'],             tasks:['chat','multilingual','code'],abliterated:false, arch:'Dense', released:'2024-06', age:'2y ago'},
  {name:'Nemotron Nano 9B v2',    provider:'NVIDIA',     params:9,    vram:5.1,  ctx:'128K',  lic:'nvidia', licLabel:'NVIDIA Open',         caps:['reasoning'],               tasks:['reasoning'],               abliterated:false, arch:'Dense', released:'2025-06', age:'10mo ago'},
  {name:'Llama 3.2 11B Vision',   provider:'Meta',       params:11,   vram:6.1,  ctx:'128K',  lic:'llama',  licLabel:'Llama 3.2 Community', caps:['chat','vision'],       tasks:['chat','vision'],            abliterated:false, arch:'Dense', released:'2024-09', age:'1 year ago'},
  {name:'Mistral Nemo 12B',       provider:'Mistral AI', params:12,   vram:6.6,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','multi'],             tasks:['chat','multilingual'],      abliterated:false, arch:'Dense', released:'2024-07', age:'1 year ago'},
  {name:'Gemma 3 12B',            provider:'Google',     params:12,   vram:6.6,  ctx:'128K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['chat','vision','reasoning'], abliterated:false, arch:'Dense', released:'2025-03', age:'1 year ago'},
  /* ── 7-16 GB ─────────────────────────────────────────────── */
  {name:'Phi-4 14B',              provider:'Microsoft',  params:14,   vram:7.7,  ctx:'16K',   lic:'mit',    licLabel:'MIT',                 caps:['chat','star','code'],      tasks:['reasoning','code'],         abliterated:false, arch:'Dense', released:'2024-12', age:'1 year ago'},
  {name:'Phi-4 14B Abliterated',  provider:'Community',  params:14,   vram:7.7,  ctx:'16K',   lic:'mit',    licLabel:'MIT',                 caps:['chat','star','code'],      tasks:['reasoning','code'],         abliterated:true,  arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'Qwen 2.5 14B',           provider:'Alibaba',    params:14,   vram:7.7,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','multi'],             tasks:['chat','multilingual','reasoning'],abliterated:false,arch:'Dense',released:'2024-09', age:'1 year ago'},
  {name:'Qwen 3 14B',             provider:'Alibaba',    params:14,   vram:7.7,  ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','reasoning','code'],         tasks:['chat','code','reasoning'],  abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'DeepSeek R1 Distill 14B',provider:'DeepSeek',   params:14,   vram:7.7,  ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning'],               tasks:['reasoning'],               abliterated:false, arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'DeepSeek R1 14B Abliterated',provider:'Community',params:14, vram:7.7,  ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning'],               tasks:['reasoning'],               abliterated:true,  arch:'Dense', released:'2025-02', age:'1 year ago'},
  {name:'GPT-OSS 20B',            provider:'OpenAI',     params:21,   vram:11.3, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','star','code'],tasks:['chat','reasoning','code'],  abliterated:false, arch:'MoE',   released:'2025-08', age:'8mo ago'},
  {name:'Mistral Small 3.1 24B',  provider:'Mistral AI', params:24,   vram:12.8, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','vision','star','code'],tasks:['chat','vision','code'],     abliterated:false, arch:'Dense', released:'2025-03', age:'1 year ago'},
  {name:'LFM2 24B',               provider:'Liquid AI',  params:24,   vram:12.8, ctx:'32K',   lic:'liquid', licLabel:'Liquid AI',           caps:['moe'],             tasks:['chat'],                     abliterated:false, arch:'MoE',   released:'2025-11', age:'5mo ago'},
  {name:'Devstral Small 2 24B',   provider:'Mistral AI', params:24,   vram:12.8, ctx:'256K',  lic:'apache', licLabel:'Apache 2.0',          caps:['code'],                  tasks:['code'],                     abliterated:false, arch:'Dense', released:'2025-12', age:'4mo ago'},
  {name:'Gemma 3 27B',            provider:'Google',     params:27,   vram:14.3, ctx:'128K',  lic:'gemma',  licLabel:'Gemma',               caps:['chat','vision','star'],tasks:['chat','vision','reasoning'], abliterated:false, arch:'Dense', released:'2025-03', age:'1 year ago'},
  {name:'Gemma 4 26B-A4B IT',     provider:'Google',     params:27,   vram:14.3, ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['moe','vision'],       tasks:['chat','vision','reasoning'], abliterated:false, arch:'MoE',   released:'2026-04', age:'5d ago'},
  {name:'Qwen 3.5 27B',           provider:'Alibaba',    params:27.8, vram:14.7, ctx:'256K',  lic:'apache', licLabel:'Apache 2.0',          caps:['reasoning','vision'],         tasks:['chat','vision','reasoning'], abliterated:false, arch:'Dense', released:'2026-02', age:'2mo ago'},
  {name:'Qwen 3 30B-A3B',         provider:'Alibaba',    params:30,   vram:15.9, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','reasoning'],   tasks:['chat','reasoning'],         abliterated:false, arch:'MoE',   released:'2025-04', age:'1 year ago'},
  /* ── > 16 GB ─────────────────────────────────────────────── */
  {name:'Qwen 2.5 32B',           provider:'Alibaba',    params:32,   vram:16.9, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','multi'],             tasks:['chat','multilingual','reasoning'],abliterated:false,arch:'Dense',released:'2024-09', age:'1 year ago'},
  {name:'Qwen 2.5 Coder 32B',     provider:'Alibaba',    params:32,   vram:16.9, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','star','code'],      tasks:['code'],                     abliterated:false, arch:'Dense', released:'2024-11', age:'1 year ago'},
  {name:'Qwen 3 32B',             provider:'Alibaba',    params:32,   vram:16.9, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['chat','reasoning','star','code'],  tasks:['chat','code','reasoning'],  abliterated:false, arch:'Dense', released:'2025-04', age:'1 year ago'},
  {name:'DeepSeek R1 Distill 32B',provider:'DeepSeek',   params:32,   vram:16.9, ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning','star'],        tasks:['reasoning'],               abliterated:false, arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'DeepSeek R1 32B Abliterated',provider:'Community',params:32, vram:16.9, ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['reasoning','star'],        tasks:['reasoning'],               abliterated:true,  arch:'Dense', released:'2025-02', age:'1 year ago'},
  {name:'Gemma 4 31B IT',         provider:'Google',     params:33,   vram:17.4, ctx:'256K',  lic:'gemma',  licLabel:'Gemma',               caps:['vision'],             tasks:['chat','vision','reasoning'], abliterated:false, arch:'Dense', released:'2026-04', age:'5d ago'},
  {name:'Command R 35B',          provider:'Cohere',     params:35,   vram:18.4, ctx:'128K',  lic:'cc',     licLabel:'CC BY-NC 4.0',        caps:['chat'],             tasks:['chat'],                     abliterated:false, arch:'Dense', released:'2024-03', age:'2y ago'},
  {name:'Mixtral 8x7B',           provider:'Mistral AI', params:47,   vram:24.6, ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','code'],       tasks:['chat','code'],              abliterated:false, arch:'MoE',   released:'2023-12', age:'2y ago'},
  {name:'Mixtral 8x7B Abliterated',provider:'Community', params:47,   vram:24.6, ctx:'32K',   lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','code'],       tasks:['chat','code'],              abliterated:true,  arch:'MoE',   released:'2024-01', age:'2y ago'},
  {name:'Llama 3.3 70B',          provider:'Meta',       params:70,   vram:36.4, ctx:'128K',  lic:'llama',  licLabel:'Llama 3.3 Community', caps:['chat','star','code'],      tasks:['chat','reasoning','code'],  abliterated:false, arch:'Dense', released:'2024-12', age:'1 year ago'},
  {name:'Llama 3.3 70B Abliterated',provider:'Community',params:70,   vram:36.4, ctx:'128K',  lic:'mit',    licLabel:'MIT',                 caps:['chat','star','code'],      tasks:['chat','reasoning','code'],  abliterated:true,  arch:'Dense', released:'2025-01', age:'1 year ago'},
  {name:'Qwen 2.5 72B',           provider:'Alibaba',    params:72,   vram:37.4, ctx:'128K',  lic:'qwen',   licLabel:'Qwen',                caps:['chat','code','multi'],             tasks:['chat','multilingual','reasoning','code'],abliterated:false,arch:'Dense',released:'2024-09', age:'1 year ago'},
  {name:'Llama 4 Scout 17B',      provider:'Meta',       params:109,  vram:56.3, ctx:'128K',  lic:'llama',  licLabel:'Llama 4 Community',   caps:['moe','chat','vision','star'],tasks:['chat','vision','reasoning'],abliterated:false,arch:'MoE',released:'2025-04', age:'1 year ago'},
  {name:'GPT-OSS 120B',           provider:'OpenAI',     params:117,  vram:60.4, ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','star','code'],tasks:['chat','reasoning','code'],  abliterated:false, arch:'MoE',   released:'2025-08', age:'8mo ago'},
  {name:'Devstral 2 123B',        provider:'Mistral AI', params:123,  vram:63.5, ctx:'256K',  lic:'mrl',    licLabel:'MRL',                 caps:['star','code'],            tasks:['code'],                     abliterated:false, arch:'Dense', released:'2025-12', age:'4mo ago'},
  {name:'Qwen 3 235B-A22B',       provider:'Alibaba',    params:235,  vram:120.9,ctx:'128K',  lic:'apache', licLabel:'Apache 2.0',          caps:['moe','chat','reasoning','code'],   tasks:['chat','code','reasoning'],  abliterated:false, arch:'MoE',   released:'2025-04', age:'1 year ago'},
  {name:'DeepSeek R1',            provider:'DeepSeek',   params:671,  vram:344.2,ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['moe','reasoning','star'],  tasks:['reasoning'],               abliterated:false, arch:'MoE',   released:'2025-01', age:'1 year ago'},
  {name:'DeepSeek R1 Abliterated',provider:'Community',  params:671,  vram:344.2,ctx:'64K',   lic:'mit',    licLabel:'MIT',                 caps:['moe','reasoning','star'],  tasks:['reasoning'],               abliterated:true,  arch:'MoE',   released:'2025-02', age:'1 year ago'},
  {name:'DeepSeek V3.2',          provider:'DeepSeek',   params:685,  vram:351.4,ctx:'128K',  lic:'mit',    licLabel:'MIT',                 caps:['moe','chat','star','code'],tasks:['chat','code','reasoning'],  abliterated:false, arch:'MoE',   released:'2025-12', age:'4mo ago'},
  {name:'Kimi K2',                provider:'Moonshot AI',params:1000, vram:512.7,ctx:'128K',  lic:'kimi',   licLabel:'Kimi',                caps:['moe','chat','star','code'],tasks:['chat','reasoning','code'],  abliterated:false, arch:'MoE',   released:'2025-07', age:'9mo ago'},
];
